{% set name = "sttr" %}
{% set version = "0.2.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abhimanyu003/sttr/archive/v{{ version }}.tar.gz
  sha256: 0369a28a944f3f2f3c5bde527572acafbeeeee1a5cf158c1dc8dd5e9f068e059

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - sttr --help

about:
  home: https://github.com/abhimanyu003/sttr
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: cross-platform, cli app to perform various operations on string
  dev_url: https://github.com/abhimanyu003/sttr

extra:
  recipe-maintainers:
    - danielnachun
