{% set name = "sttr" %}
{% set version = "0.2.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/abhimanyu003/sttr/archive/v{{ version }}.tar.gz
  sha256: e9340c65c22d3016f9e4fe0a7f414bd1a8d8463203806c28b09a79889c805d76

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - sttr --help

about:
  home: https://github.com/abhimanyu003/sttr
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: cross-platform, cli app to perform various operations on string
  dev_url: https://github.com/abhimanyu003/sttr

extra:
  recipe-maintainers:
    - danielnachun
