schema_version: 1

context:
  version: "0.2.29"

package:
  name: sttr
  version: ${{ version }}

source:
  url: https://github.com/abhimanyu003/sttr/archive/v${{ version }}.tar.gz
  sha256: ee9031656861671fd6103fb8d74cede331d92c39afd13b95d0b323debf26bf84

build:
  number: 0

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - sttr --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: cross-platform, cli app to perform various operations on string
  homepage: https://github.com/abhimanyu003/sttr
  repository: https://github.com/abhimanyu003/sttr

extra:
  recipe-maintainers:
    - danielnachun
